# Generated by Django 5.2.6 on 2025-11-11 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='טלפון')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
