# Generated by Django 5.2.8 on 2025-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='regulations_document',
            field=models.FileField(blank=True, null=True, upload_to='regulations/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='אימייל'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='טלפון'),
        ),
    ]
