# Generated by Django 5.2.6 on 2025-10-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_side', models.CharField(max_length=20)),
                ('groom_side', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=40)),
                ('date', models.DateField(blank=True, null=True, verbose_name='תאריך האירוע')),
                ('date_gregorian', models.DateField(blank=True, null=True, verbose_name='תאריך לועזי')),
                ('hall', models.CharField(blank=True, max_length=255, null=True, verbose_name='אולם')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name="סט' נוספים")),
                ('video', models.BooleanField(default=False, verbose_name='וידאו')),
                ('status', models.CharField(choices=[('contacted', 'יצר קשר'), ('closed', 'סגר עסקה'), ('served', 'קיבל שירות')], default='contacted', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'לא שילם'), ('partial', 'שילם חלקית'), ('paid', 'שילם במלואו')], default='unpaid', max_length=20)),
            ],
        ),
    ]
