# Generated by Django 5.2.6 on 2025-10-26 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(max_length=40, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='bride_side',
            field=models.CharField(max_length=20, verbose_name='צד כלה'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='תאריך האירוע'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='אימייל'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='groom_side',
            field=models.CharField(max_length=20, verbose_name='צד בעל'),
        ),
    ]
