# Generated by Django 5.2.6 on 2025-10-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='additional_crew',
            field=models.TextField(blank=True, null=True, verbose_name='סטילס נוספים'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assistent',
            field=models.BooleanField(default=False, verbose_name='עוזר'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='additional_details',
            field=models.TextField(blank=True, null=True, verbose_name='פרטים נוספים'),
        ),
    ]
