# Generated by Django 5.2.6 on 2025-10-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_additional_crew_lead_assistent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebrew_day', models.CharField(max_length=10, verbose_name='יום עברי')),
                ('hebrew_month', models.CharField(max_length=20, verbose_name='חודש עברי')),
                ('hebrew_year', models.CharField(max_length=10, verbose_name='שנה עברית')),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='date',
        ),
        migrations.AddField(
            model_name='lead',
            name='event_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.eventdate'),
        ),
    ]
