# Generated by Django 5.2.6 on 2025-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_eventdate_remove_lead_date_lead_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='event_date',
        ),
        migrations.AddField(
            model_name='lead',
            name='hebrew_day',
            field=models.CharField(default='-', max_length=10, verbose_name='יום עברי'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hebrew_month',
            field=models.CharField(default='-', max_length=20, verbose_name='חודש עברי'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hebrew_year',
            field=models.CharField(default='-', max_length=10, verbose_name='שנה עברית'),
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
