# Generated by Django 5.2.6 on 2025-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_remove_lead_event_date_lead_hebrew_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='day',
            field=models.CharField(blank=True, choices=[('א', 'א'), ('ב', 'ב'), ('ג', 'ג'), ('ד', 'ד'), ('ה', 'ה'), ('ו', 'ו')], default='', max_length=1, verbose_name='יום'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hebrew_day',
            field=models.CharField(default='', max_length=10, verbose_name='יום עברי'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hebrew_month',
            field=models.CharField(blank=True, choices=[('תשרי', 'תשרי'), ('חשוון', 'חשוון'), ('כסלו', 'כסלו'), ('טבת', 'טבת'), ('שבט', 'שבט'), ('אדר', 'אדר'), ('ניסן', 'ניסן'), ('אייר', 'אייר'), ('סיון', 'סיון'), ('תמוז', 'תמוז'), ('אב', 'אב'), ('אלול', 'אלול')], default='', max_length=10, verbose_name='חודש עברי'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hebrew_year',
            field=models.CharField(default='', max_length=10, verbose_name='שנה עברית'),
        ),
    ]
