# Generated by Django 5.2.6 on 2025-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_lead_day_alter_lead_hebrew_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='concat_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='כתובת'),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_additional_crew',
            field=models.BooleanField(default=False, verbose_name='רוצים צלמת בנוסף?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hour',
            field=models.CharField(blank=True, default='לא נקבע', max_length=10, verbose_name='שעה'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='additional_crew',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='צלמת'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='additional_details',
            field=models.TextField(blank=True, default='', verbose_name='פרטים נוספים'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assistent',
            field=models.CharField(blank=True, default='❓', max_length=50, verbose_name='עוזר'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hall',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='אולם'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hebrew_day',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='יום עברי'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hebrew_year',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='שנה עברית'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='video',
            field=models.CharField(blank=True, default='❓', max_length=50, verbose_name='וידאו'),
        ),
    ]
