# Generated by Django 5.2.6 on 2025-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_contact_concat_address_lead_has_additional_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='טלפון'),
        ),
    ]
