# Generated by Django 5.2.6 on 2025-11-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
