# Generated by Django 5.2.6 on 2025-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_lead_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='שם פרטי'),
        ),
        migrations.AddField(
            model_name='contact',
            name='second_name',
            field=models.CharField(default='', max_length=100, verbose_name='שם משפחה'),
        ),
    ]
