# Generated by Django 5.2.6 on 2025-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_remove_contact_name_remove_lead_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='קשר לבעלי השמחה:'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='כתובת האולם'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='bride_side',
            field=models.CharField(max_length=20, verbose_name='משפחת הכלה'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='groom_side',
            field=models.CharField(max_length=20, verbose_name='משפחת החתן'),
        ),
    ]
