# Generated by Django 5.2.6 on 2025-11-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_remove_contact_notes_alter_contact_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment_method',
            field=models.CharField(choices=[('credit-card', 'אשראי'), ('bank-transfer', 'העברה בנקאית'), ('cash', 'מזומן')], default='', max_length=20, verbose_name='אמצעי תשלום'),
        ),
    ]
